export const REVOLUT_X_UNIVERSE_USD = {
  quoteCurrency: "USD",
  source: "Manual Revolut X screenshot universe supplied by Tom",
  updatedAt: new Date().toISOString(),
  symbols: [
    "BTC", "ETH", "BNB", "XRP", "SOL", "TRX", "HYPE", "DOGE", "XLM", "LINK",
    "ADA", "BCH", "LTC", "HBAR", "SUI", "AVAX", "CRO", "SHIB", "NEAR", "WLFI",
    "UNI", "WLD", "ONDO", "AAVE", "DOT", "ICP", "SKY", "MORPHO", "ETC", "PEPE",
    "QNT", "RENDER", "ATOM", "ALGO", "POL", "JUP", "ENA", "VVV", "FLR", "FIL",
    "XDC", "APT", "INJ", "ARB", "DASH", "JTO", "TRUMP", "FET", "PENGU", "VET",
    "BONK", "TIA", "SEI", "SPX", "STX", "GRASS", "CRV", "PYTH", "XTZ", "ZZ",
    "JASMY", "OP", "FLOKI", "LDO", "ZRO", "AKT", "GRT", "STRK", "CHZ", "EIGEN",
    "ENS", "AXS", "WIF", "SYRUP", "RAY", "COMP", "XCN", "APE", "KAITO", "BAT",
    "SAND", "MANA", "TRAC", "IP", "GALA", "IMX", "ZK", "CVX", "GLM", "1INCH",
    "ATH", "COW", "SNX", "ARKM", "EGLD", "LPT", "ZEN", "RSR", "KTA", "ORCA",
    "MELANIA", "ZRX", "AIOZ", "DEGEN", "IO", "NMR", "SAFE", "YFI", "W", "BERA",
    "KSM", "TURBO", "SUPER", "SPK", "HNT", "MINA", "KAVA", "TOSHI", "ROSE",
    "FLOW", "XYO", "POPCAT", "AMP", "SUSHI", "BLUR", "MOG", "PNUT", "REQ", "MOODENG",
    "RED", "NOT", "MASK", "T", "PROVE", "CELO", "TRB", "VTHO", "SQD", "ME",
    "UMA", "ANKR", "RPL", "API3", "ZORA", "MEW", "ALEO", "ACX", "BNT", "OCEAN",
    "OSMO", "SWFTC", "IOTX", "REZ", "NEIRO", "BAND", "XAN", "COTI", "STG", "AUCTION",
    "RIZE", "PUNDIX", "B3", "ILV", "EUL", "GMT", "POWR", "VELO", "GIGA", "FIDA",
    "SKL", "RLC", "WOO", "EDGE", "PRO", "METIS", "CTSI", "ABT", "DOGS", "AUDIO",
    "AGLD", "KNC", "FAI", "LQTY", "AURORA", "SXT", "CVC", "SPELL", "LRC",
    "CLANKER", "PRIME", "BICO", "BIGTIME", "LAYER", "MAGIC", "PONKE", "TAIKO", "ZKC", "C98",
    "LA", "DIA", "TNSR", "PARTI", "ALICE", "KERNEL", "RAD", "CELR", "STORJ", "HOPR",
    "NCT", "MNDE", "BOBA", "OGN", "GODS", "RARE", "DRIFT", "HONEY", "TOKEN", "SD",
    "POND", "QI", "ELA", "ARPA", "PYR", "FORT", "ASM", "HFT", "BADGER", "ACS",
    "TREE", "COOKIE", "POLS", "GTC", "BAL", "ALCX", "TAI", "PNG", "KRL", "GFI",
    "SPA", "NKN", "DYDX", "NEON", "MATH", "DOGINME", "CXT", "LMWR", "ZKJ", "MLN",
    "BLZ", "SWELL", "AVT", "OXT", "SUKU", "FARM", "PRCL", "SHDW", "DIMO", "GHST",
    "AB", "KARRAT", "ALEPH", "PIRATE", "TON", "FORTH", "RARI", "BENJI", "MDT", "FIS",
    "PERP", "IDEX", "GST", "LRDS", "TRU", "AST", "VOXEL", "FX", "PLA", "BTRST",
    "ACH", "AERGO", "HIGH", "SHPING", "MIR"
  ]
} as const;

export type RevolutXSymbol = (typeof REVOLUT_X_UNIVERSE_USD.symbols)[number];

export type RevolutXAsset = {
  symbol: string;
  cgId?: string;
  name?: string;
  assumption?: string;
};

export const REVOLUT_X_PROVIDER_IDS: Record<string, RevolutXAsset> = {
  "1INCH": { symbol: "1INCH", cgId: "1inch", name: "1inch" },
  AB: { symbol: "AB", name: "AB", assumption: "Ambiguous ticker; no reliable CoinGecko provider ID found, so it is reported unresolved." },
  ABT: { symbol: "ABT", cgId: "arcblock", name: "Arcblock" },
  ACS: { symbol: "ACS", cgId: "access-protocol", name: "Access Protocol" },
  ACH: { symbol: "ACH", cgId: "alchemy-pay", name: "Alchemy Pay" },
  AAVE: { symbol: "AAVE", cgId: "aave", name: "Aave" },
  ACX: { symbol: "ACX", cgId: "across-protocol", name: "Across Protocol" },
  ADA: { symbol: "ADA", cgId: "cardano", name: "Cardano" },
  AERGO: { symbol: "AERGO", cgId: "aergo", name: "Aergo" },
  AGLD: { symbol: "AGLD", cgId: "adventure-gold", name: "Adventure Gold" },
  AIOZ: { symbol: "AIOZ", cgId: "aioz-network", name: "AIOZ Network" },
  AKT: { symbol: "AKT", cgId: "akash-network", name: "Akash Network" },
  ALCX: { symbol: "ALCX", cgId: "alchemix", name: "Alchemix" },
  ALEO: { symbol: "ALEO", cgId: "aleo", name: "Aleo" },
  ALEPH: { symbol: "ALEPH", cgId: "aleph", name: "Aleph Cloud" },
  ALGO: { symbol: "ALGO", cgId: "algorand", name: "Algorand" },
  ALICE: { symbol: "ALICE", cgId: "my-neighbor-alice", name: "My Neighbor Alice" },
  AMP: { symbol: "AMP", cgId: "amp-token", name: "Amp" },
  ANKR: { symbol: "ANKR", cgId: "ankr", name: "Ankr" },
  APE: { symbol: "APE", cgId: "apecoin", name: "ApeCoin" },
  API3: { symbol: "API3", cgId: "api3", name: "API3" },
  APT: { symbol: "APT", cgId: "aptos", name: "Aptos" },
  ARB: { symbol: "ARB", cgId: "arbitrum", name: "Arbitrum" },
  ARKM: { symbol: "ARKM", cgId: "arkham", name: "Arkham" },
  ARPA: { symbol: "ARPA", cgId: "arpa", name: "ARPA" },
  ASM: { symbol: "ASM", cgId: "assemble-protocol", name: "Assemble AI" },
  AST: { symbol: "AST", cgId: "airswap", name: "AirSwap" },
  ATH: { symbol: "ATH", cgId: "aethir", name: "Aethir" },
  ATOM: { symbol: "ATOM", cgId: "cosmos", name: "Cosmos" },
  AUCTION: { symbol: "AUCTION", cgId: "auction", name: "Bounce" },
  AUDIO: { symbol: "AUDIO", cgId: "audius", name: "Audius" },
  AURORA: { symbol: "AURORA", cgId: "aurora-near", name: "Aurora" },
  AVAX: { symbol: "AVAX", cgId: "avalanche-2", name: "Avalanche" },
  AVT: { symbol: "AVT", cgId: "aventus", name: "Aventus" },
  AXS: { symbol: "AXS", cgId: "axie-infinity", name: "Axie Infinity" },
  B3: { symbol: "B3", cgId: "b3", name: "B3" },
  BADGER: { symbol: "BADGER", cgId: "badger-dao", name: "Badger" },
  BAL: { symbol: "BAL", cgId: "balancer", name: "Balancer" },
  BAND: { symbol: "BAND", cgId: "band-protocol", name: "Band Protocol" },
  BAT: { symbol: "BAT", cgId: "basic-attention-token", name: "BAT" },
  BCH: { symbol: "BCH", cgId: "bitcoin-cash", name: "Bitcoin Cash" },
  BENJI: { symbol: "BENJI", cgId: "basenji", name: "Basenji", assumption: "Ambiguous ticker; mapped to Basenji." },
  BERA: { symbol: "BERA", cgId: "berachain-bera", name: "Berachain" },
  BICO: { symbol: "BICO", cgId: "biconomy", name: "Biconomy" },
  BIGTIME: { symbol: "BIGTIME", cgId: "big-time", name: "Big Time" },
  BLUR: { symbol: "BLUR", cgId: "blur", name: "Blur" },
  BLZ: { symbol: "BLZ", cgId: "bluzelle", name: "Bluzelle" },
  BNT: { symbol: "BNT", cgId: "bancor", name: "Bancor Network" },
  BNB: { symbol: "BNB", cgId: "binancecoin", name: "BNB" },
  BOBA: { symbol: "BOBA", cgId: "boba-network", name: "Boba Network" },
  BONK: { symbol: "BONK", cgId: "bonk", name: "Bonk" },
  BTC: { symbol: "BTC", cgId: "bitcoin", name: "Bitcoin" },
  BTRST: { symbol: "BTRST", cgId: "braintrust", name: "Braintrust" },
  C98: { symbol: "C98", cgId: "coin98", name: "Coin98" },
  CELO: { symbol: "CELO", cgId: "celo", name: "Celo" },
  CELR: { symbol: "CELR", cgId: "celer-network", name: "Celer Network" },
  CHZ: { symbol: "CHZ", cgId: "chiliz", name: "Chiliz" },
  CLANKER: { symbol: "CLANKER", cgId: "clanker", name: "Clanker", assumption: "Ambiguous ticker; mapped to Clanker." },
  COMP: { symbol: "COMP", cgId: "compound-governance-token", name: "Compound" },
  COOKIE: { symbol: "COOKIE", cgId: "cookie", name: "Cookie DAO" },
  COTI: { symbol: "COTI", cgId: "coti", name: "COTI" },
  COW: { symbol: "COW", cgId: "cow-protocol", name: "CoW Protocol" },
  CRO: { symbol: "CRO", cgId: "crypto-com-chain", name: "Cronos" },
  CRV: { symbol: "CRV", cgId: "curve-dao-token", name: "Curve" },
  CTSI: { symbol: "CTSI", cgId: "cartesi", name: "Cartesi" },
  CVC: { symbol: "CVC", cgId: "civic", name: "Civic" },
  CVX: { symbol: "CVX", cgId: "convex-finance", name: "Convex Finance" },
  CXT: { symbol: "CXT", cgId: "covalent-x-token", name: "Covalent X Token" },
  DASH: { symbol: "DASH", cgId: "dash", name: "Dash" },
  DEGEN: { symbol: "DEGEN", cgId: "degen-base", name: "Degen" },
  DIA: { symbol: "DIA", cgId: "dia-data", name: "DIA" },
  DIMO: { symbol: "DIMO", cgId: "dimo", name: "DIMO" },
  DOGE: { symbol: "DOGE", cgId: "dogecoin", name: "Dogecoin" },
  DOGINME: { symbol: "DOGINME", cgId: "doginme", name: "doginme" },
  DOGS: { symbol: "DOGS", cgId: "dogs-2", name: "Dogs" },
  DOT: { symbol: "DOT", cgId: "polkadot", name: "Polkadot" },
  DRIFT: { symbol: "DRIFT", cgId: "drift-protocol", name: "Drift" },
  DYDX: { symbol: "DYDX", cgId: "dydx", name: "dYdX" },
  EDGE: { symbol: "EDGE", cgId: "definitive", name: "Definitive", assumption: "Ambiguous ticker; mapped to CoinGecko id definitive." },
  EGLD: { symbol: "EGLD", cgId: "elrond-erd-2", name: "MultiversX" },
  EIGEN: { symbol: "EIGEN", cgId: "eigenlayer", name: "EigenLayer" },
  ELA: { symbol: "ELA", cgId: "elastos", name: "Elastos" },
  ENA: { symbol: "ENA", cgId: "ethena", name: "Ethena" },
  ENS: { symbol: "ENS", cgId: "ethereum-name-service", name: "Ethereum Name Service" },
  ETC: { symbol: "ETC", cgId: "ethereum-classic", name: "Ethereum Classic" },
  ETH: { symbol: "ETH", cgId: "ethereum", name: "Ethereum" },
  EUL: { symbol: "EUL", cgId: "euler", name: "Euler" },
  FAI: { symbol: "FAI", cgId: "freysa-ai", name: "Freysa AI" },
  FARM: { symbol: "FARM", cgId: "harvest-finance", name: "Harvest Finance" },
  FET: { symbol: "FET", cgId: "fetch-ai", name: "Artificial Superintelligence Alliance" },
  FIDA: { symbol: "FIDA", cgId: "bonfida", name: "Bonfida", assumption: "Ambiguous ticker; mapped to Bonfida." },
  FIL: { symbol: "FIL", cgId: "filecoin", name: "Filecoin" },
  FIS: { symbol: "FIS", cgId: "stafi", name: "StaFi" },
  FLR: { symbol: "FLR", cgId: "flare-networks", name: "Flare" },
  FLOKI: { symbol: "FLOKI", cgId: "floki", name: "FLOKI" },
  FLOW: { symbol: "FLOW", cgId: "flow", name: "Flow" },
  FORT: { symbol: "FORT", cgId: "forta", name: "Forta" },
  FORTH: { symbol: "FORTH", cgId: "ampleforth-governance-token", name: "Ampleforth Governance" },
  FX: { symbol: "FX", name: "FX", assumption: "Ambiguous ticker; no reliable CoinGecko provider ID found, so it is reported unresolved." },
  GALA: { symbol: "GALA", cgId: "gala", name: "Gala" },
  GFI: { symbol: "GFI", cgId: "goldfinch", name: "Goldfinch" },
  GMT: { symbol: "GMT", cgId: "stepn", name: "GMT" },
  GHST: { symbol: "GHST", cgId: "aavegotchi", name: "Aavegotchi" },
  GIGA: { symbol: "GIGA", cgId: "gigachad-2", name: "Gigachad" },
  GLM: { symbol: "GLM", cgId: "golem", name: "Golem" },
  GODS: { symbol: "GODS", cgId: "gods-unchained", name: "Gods Unchained" },
  GRASS: { symbol: "GRASS", cgId: "grass", name: "Grass" },
  GRT: { symbol: "GRT", cgId: "the-graph", name: "The Graph" },
  GST: { symbol: "GST", cgId: "green-satoshi-token", name: "Green Satoshi Token", assumption: "Ambiguous ticker; mapped to Solana Green Satoshi Token." },
  GTC: { symbol: "GTC", cgId: "gitcoin", name: "Gitcoin" },
  HBAR: { symbol: "HBAR", cgId: "hedera-hashgraph", name: "Hedera" },
  HFT: { symbol: "HFT", cgId: "hashflow", name: "Hashflow" },
  HIGH: { symbol: "HIGH", cgId: "highstreet", name: "Highstreet" },
  HNT: { symbol: "HNT", cgId: "helium", name: "Helium" },
  HONEY: { symbol: "HONEY", cgId: "hivemapper", name: "Hivemapper" },
  HOPR: { symbol: "HOPR", cgId: "hopr", name: "HOPR" },
  HYPE: { symbol: "HYPE", cgId: "hyperliquid", name: "Hyperliquid" },
  ICP: { symbol: "ICP", cgId: "internet-computer", name: "Internet Computer" },
  IDEX: { symbol: "IDEX", cgId: "aurora-dao", name: "IDEX" },
  ILV: { symbol: "ILV", cgId: "illuvium", name: "Illuvium" },
  IMX: { symbol: "IMX", cgId: "immutable-x", name: "Immutable" },
  INJ: { symbol: "INJ", cgId: "injective-protocol", name: "Injective" },
  IO: { symbol: "IO", cgId: "io", name: "io.net" },
  IOTX: { symbol: "IOTX", cgId: "iotex", name: "IoTeX" },
  IP: { symbol: "IP", cgId: "story-2", name: "Story", assumption: "Ambiguous ticker; mapped to Story." },
  JASMY: { symbol: "JASMY", cgId: "jasmycoin", name: "JasmyCoin" },
  JTO: { symbol: "JTO", cgId: "jito-governance-token", name: "Jito" },
  JUP: { symbol: "JUP", cgId: "jupiter-exchange-solana", name: "Jupiter" },
  KAITO: { symbol: "KAITO", cgId: "kaito", name: "Kaito" },
  KARRAT: { symbol: "KARRAT", cgId: "karrat", name: "Karrat" },
  KAVA: { symbol: "KAVA", cgId: "kava", name: "Kava" },
  KERNEL: { symbol: "KERNEL", cgId: "kernel-2", name: "Kernel" },
  KNC: { symbol: "KNC", cgId: "kyber-network-crystal", name: "Kyber Network" },
  KRL: { symbol: "KRL", cgId: "kryll", name: "Kryll" },
  KSM: { symbol: "KSM", cgId: "kusama", name: "Kusama" },
  KTA: { symbol: "KTA", cgId: "keeta", name: "Keeta", assumption: "Ambiguous ticker; mapped to Keeta." },
  LA: { symbol: "LA", cgId: "latoken", name: "LATOKEN", assumption: "Ambiguous ticker; mapped to LATOKEN." },
  LAYER: { symbol: "LAYER", cgId: "solayer", name: "Solayer" },
  LDO: { symbol: "LDO", cgId: "lido-dao", name: "Lido" },
  LINK: { symbol: "LINK", cgId: "chainlink", name: "Chainlink" },
  LMWR: { symbol: "LMWR", cgId: "limewire-token", name: "LimeWire" },
  LPT: { symbol: "LPT", cgId: "livepeer", name: "Livepeer" },
  LQTY: { symbol: "LQTY", cgId: "liquity", name: "Liquity" },
  LRC: { symbol: "LRC", cgId: "loopring", name: "Loopring" },
  LRDS: { symbol: "LRDS", cgId: "blocklords", name: "BLOCKLORDS" },
  LTC: { symbol: "LTC", cgId: "litecoin", name: "Litecoin" },
  MAGIC: { symbol: "MAGIC", cgId: "magic", name: "Treasure" },
  MANA: { symbol: "MANA", cgId: "decentraland", name: "Decentraland" },
  MASK: { symbol: "MASK", cgId: "mask-network", name: "Mask Network" },
  MATH: { symbol: "MATH", cgId: "math", name: "MATH" },
  MDT: { symbol: "MDT", cgId: "measurable-data-token", name: "Measurable Data Token" },
  ME: { symbol: "ME", cgId: "magic-eden", name: "Magic Eden", assumption: "Ambiguous ticker; mapped to Magic Eden." },
  MELANIA: { symbol: "MELANIA", cgId: "melania-meme", name: "Melania Meme" },
  METIS: { symbol: "METIS", cgId: "metis-token", name: "Metis" },
  MEW: { symbol: "MEW", cgId: "cat-in-a-dogs-world", name: "cat in a dogs world" },
  MINA: { symbol: "MINA", cgId: "mina-protocol", name: "Mina" },
  MIR: { symbol: "MIR", cgId: "mirror-protocol", name: "Mirror Protocol" },
  MLN: { symbol: "MLN", cgId: "melon", name: "Enzyme" },
  MNDE: { symbol: "MNDE", cgId: "marinade", name: "Marinade" },
  MOG: { symbol: "MOG", cgId: "mog-coin", name: "Mog Coin" },
  MOODENG: { symbol: "MOODENG", cgId: "moo-deng", name: "Moo Deng" },
  MORPHO: { symbol: "MORPHO", cgId: "morpho", name: "Morpho" },
  NCT: { symbol: "NCT", cgId: "toucan-protocol-base-carbon-tonne", name: "Toucan Protocol" },
  NEAR: { symbol: "NEAR", cgId: "near", name: "NEAR Protocol" },
  NEIRO: { symbol: "NEIRO", cgId: "neiro-3", name: "Neiro", assumption: "Ambiguous ticker; mapped to CoinGecko id neiro-3." },
  NEON: { symbol: "NEON", cgId: "neon", name: "Neon" },
  NKN: { symbol: "NKN", cgId: "nkn", name: "NKN" },
  NMR: { symbol: "NMR", cgId: "numeraire", name: "Numeraire" },
  NOT: { symbol: "NOT", cgId: "notcoin", name: "Notcoin" },
  OCEAN: { symbol: "OCEAN", cgId: "ocean-protocol", name: "Ocean Protocol" },
  OGN: { symbol: "OGN", cgId: "origin-protocol", name: "Origin Protocol" },
  ONDO: { symbol: "ONDO", cgId: "ondo-finance", name: "Ondo" },
  OP: { symbol: "OP", cgId: "optimism", name: "Optimism" },
  ORCA: { symbol: "ORCA", cgId: "orca", name: "Orca" },
  OSMO: { symbol: "OSMO", cgId: "osmosis", name: "Osmosis" },
  OXT: { symbol: "OXT", cgId: "orchid-protocol", name: "Orchid" },
  PARTI: { symbol: "PARTI", cgId: "particle-network", name: "Particle Network", assumption: "Ambiguous ticker; mapped to Particle Network." },
  PENGU: { symbol: "PENGU", cgId: "pudgy-penguins", name: "Pudgy Penguins" },
  PEPE: { symbol: "PEPE", cgId: "pepe", name: "Pepe" },
  PERP: { symbol: "PERP", cgId: "perpetual-protocol", name: "Perpetual Protocol" },
  PIRATE: { symbol: "PIRATE", cgId: "pirate-chain", name: "Pirate Chain" },
  PLA: { symbol: "PLA", cgId: "playdapp", name: "PlayDapp" },
  PNG: { symbol: "PNG", cgId: "pangolin", name: "Pangolin" },
  PNUT: { symbol: "PNUT", cgId: "peanut-the-squirrel", name: "Peanut the Squirrel" },
  POL: { symbol: "POL", cgId: "polygon-ecosystem-token", name: "Polygon Ecosystem Token" },
  POLS: { symbol: "POLS", cgId: "polkastarter", name: "Polkastarter" },
  POND: { symbol: "POND", cgId: "marlin", name: "Marlin" },
  PONKE: { symbol: "PONKE", cgId: "ponke", name: "Ponke" },
  POPCAT: { symbol: "POPCAT", cgId: "popcat", name: "Popcat" },
  POWR: { symbol: "POWR", cgId: "power-ledger", name: "Powerledger" },
  PRCL: { symbol: "PRCL", cgId: "parcl", name: "Parcl" },
  PRIME: { symbol: "PRIME", cgId: "echelon-prime", name: "Echelon Prime" },
  PRO: { symbol: "PRO", cgId: "propy", name: "Propy", assumption: "Ambiguous ticker; mapped to Propy." },
  PROVE: { symbol: "PROVE", cgId: "succinct", name: "Succinct" },
  PUNDIX: { symbol: "PUNDIX", cgId: "pundi-x-2", name: "Pundi X" },
  PYR: { symbol: "PYR", cgId: "vulcan-forged", name: "Vulcan Forged" },
  PYTH: { symbol: "PYTH", cgId: "pyth-network", name: "Pyth Network" },
  QI: { symbol: "QI", cgId: "benqi", name: "BENQI" },
  QNT: { symbol: "QNT", cgId: "quant-network", name: "Quant" },
  RAD: { symbol: "RAD", cgId: "radicle", name: "Radicle" },
  RARE: { symbol: "RARE", cgId: "superrare", name: "SuperRare" },
  RARI: { symbol: "RARI", cgId: "rarible", name: "Rarible" },
  RAY: { symbol: "RAY", cgId: "raydium", name: "Raydium" },
  RED: { symbol: "RED", cgId: "redstone-oracles", name: "RedStone", assumption: "Ambiguous ticker; mapped to RedStone." },
  RENDER: { symbol: "RENDER", cgId: "render-token", name: "Render" },
  REQ: { symbol: "REQ", cgId: "request-network", name: "Request" },
  REZ: { symbol: "REZ", cgId: "renzo", name: "Renzo" },
  RIZE: { symbol: "RIZE", cgId: "rize", name: "RIZE", assumption: "Ambiguous ticker; mapped to RIZE." },
  RLC: { symbol: "RLC", cgId: "iexec-rlc", name: "iExec RLC" },
  ROSE: { symbol: "ROSE", cgId: "oasis-network", name: "Oasis Network" },
  RPL: { symbol: "RPL", cgId: "rocket-pool", name: "Rocket Pool" },
  RSR: { symbol: "RSR", cgId: "reserve-rights-token", name: "Reserve Rights" },
  SAFE: { symbol: "SAFE", cgId: "safe", name: "Safe" },
  SAND: { symbol: "SAND", cgId: "the-sandbox", name: "The Sandbox" },
  SD: { symbol: "SD", cgId: "stader", name: "Stader" },
  SEI: { symbol: "SEI", cgId: "sei-network", name: "Sei" },
  SHDW: { symbol: "SHDW", cgId: "genesysgo-shadow", name: "Shadow Token" },
  SHIB: { symbol: "SHIB", cgId: "shiba-inu", name: "Shiba Inu" },
  SHPING: { symbol: "SHPING", cgId: "shping", name: "SHPING" },
  SKY: { symbol: "SKY", cgId: "sky", name: "Sky" },
  SKL: { symbol: "SKL", cgId: "skale", name: "SKALE" },
  SNX: { symbol: "SNX", cgId: "havven", name: "Synthetix" },
  SOL: { symbol: "SOL", cgId: "solana", name: "Solana" },
  SPA: { symbol: "SPA", cgId: "sperax", name: "Sperax" },
  SPELL: { symbol: "SPELL", cgId: "spell-token", name: "Spell" },
  SPK: { symbol: "SPK", cgId: "spark-2", name: "Spark" },
  SPX: { symbol: "SPX", cgId: "spx6900", name: "SPX6900" },
  SQD: { symbol: "SQD", cgId: "subsquid", name: "Subsquid", assumption: "Ambiguous ticker; mapped to Subsquid." },
  STG: { symbol: "STG", cgId: "stargate-finance", name: "Stargate Finance" },
  STORJ: { symbol: "STORJ", cgId: "storj", name: "Storj" },
  STRK: { symbol: "STRK", cgId: "starknet", name: "Starknet" },
  STX: { symbol: "STX", cgId: "blockstack", name: "Stacks" },
  SUI: { symbol: "SUI", cgId: "sui", name: "Sui" },
  SUKU: { symbol: "SUKU", cgId: "suku", name: "SUKU" },
  SUPER: { symbol: "SUPER", cgId: "superfarm", name: "SuperVerse" },
  SUSHI: { symbol: "SUSHI", cgId: "sushi", name: "SushiSwap" },
  SWELL: { symbol: "SWELL", cgId: "swell-network", name: "Swell" },
  SWFTC: { symbol: "SWFTC", cgId: "swftcoin", name: "SWFTCOIN" },
  SXT: { symbol: "SXT", cgId: "space-and-time", name: "Space and Time", assumption: "Ambiguous ticker; mapped to Space and Time." },
  SYRUP: { symbol: "SYRUP", cgId: "syrup", name: "Maple Finance" },
  T: { symbol: "T", cgId: "threshold-network-token", name: "Threshold", assumption: "Ambiguous ticker; mapped to Threshold." },
  TAI: { symbol: "TAI", cgId: "tars-protocol", name: "TARS AI" },
  TAIKO: { symbol: "TAIKO", cgId: "taiko", name: "Taiko" },
  TIA: { symbol: "TIA", cgId: "celestia", name: "Celestia" },
  TNSR: { symbol: "TNSR", cgId: "tensor", name: "Tensor" },
  TOKEN: { symbol: "TOKEN", cgId: "tokenfi", name: "TokenFi", assumption: "Ambiguous ticker; mapped to TokenFi." },
  TON: { symbol: "TON", cgId: "the-open-network", name: "Toncoin", assumption: "Ambiguous ticker; mapped to Toncoin." },
  TOSHI: { symbol: "TOSHI", cgId: "toshi", name: "Toshi" },
  TRAC: { symbol: "TRAC", cgId: "origintrail", name: "OriginTrail" },
  TRB: { symbol: "TRB", cgId: "tellor", name: "Tellor" },
  TREE: { symbol: "TREE", cgId: "treehouse", name: "Treehouse", assumption: "Ambiguous ticker; mapped to Treehouse." },
  TRU: { symbol: "TRU", cgId: "truefi", name: "TrueFi" },
  TRUMP: { symbol: "TRUMP", cgId: "official-trump", name: "Official TRUMP" },
  TRX: { symbol: "TRX", cgId: "tron", name: "Tron" },
  TURBO: { symbol: "TURBO", cgId: "turbo", name: "Turbo" },
  UMA: { symbol: "UMA", cgId: "uma", name: "UMA" },
  UNI: { symbol: "UNI", cgId: "uniswap", name: "Uniswap" },
  VELO: { symbol: "VELO", cgId: "velo", name: "Velo" },
  VET: { symbol: "VET", cgId: "vechain", name: "VeChain" },
  VOXEL: { symbol: "VOXEL", cgId: "voxies", name: "Voxies" },
  VTHO: { symbol: "VTHO", cgId: "vethor-token", name: "VeThor" },
  VVV: { symbol: "VVV", cgId: "venice-token", name: "Venice Token" },
  W: { symbol: "W", cgId: "wormhole", name: "Wormhole", assumption: "Ambiguous ticker; mapped to Wormhole." },
  WIF: { symbol: "WIF", cgId: "dogwifcoin", name: "dogwifhat" },
  WLFI: { symbol: "WLFI", cgId: "world-liberty-financial", name: "World Liberty Financial" },
  WLD: { symbol: "WLD", cgId: "worldcoin-wld", name: "Worldcoin" },
  WOO: { symbol: "WOO", cgId: "woo-network", name: "WOO" },
  XAN: { symbol: "XAN", cgId: "anoma", name: "Anoma", assumption: "Ambiguous ticker; mapped to Anoma." },
  XCN: { symbol: "XCN", cgId: "chain-2", name: "Onyxcoin" },
  XDC: { symbol: "XDC", cgId: "xdce-crowd-sale", name: "XDC Network" },
  XLM: { symbol: "XLM", cgId: "stellar", name: "Stellar" },
  XRP: { symbol: "XRP", cgId: "ripple", name: "XRP" },
  XTZ: { symbol: "XTZ", cgId: "tezos", name: "Tezos" },
  XYO: { symbol: "XYO", cgId: "xyo-network", name: "XYO" },
  YFI: { symbol: "YFI", cgId: "yearn-finance", name: "Yearn" },
  ZEN: { symbol: "ZEN", cgId: "zencash", name: "Horizen" },
  ZK: { symbol: "ZK", cgId: "zksync", name: "ZKsync" },
  ZKC: { symbol: "ZKC", cgId: "boundless", name: "Boundless", assumption: "Ambiguous ticker; mapped to Boundless." },
  ZKJ: { symbol: "ZKJ", cgId: "polyhedra-network", name: "Polyhedra Network" },
  ZORA: { symbol: "ZORA", cgId: "zora", name: "Zora" },
  ZRO: { symbol: "ZRO", cgId: "layerzero", name: "LayerZero" },
  ZRX: { symbol: "ZRX", cgId: "0x", name: "0x Protocol" },
  ZZ: { symbol: "ZZ", cgId: "zircuit", name: "Zircuit" },
};

export function getRevolutXUniverseAssets() {
  const seen = new Set<string>();
  const duplicateSymbolsRemoved: string[] = [];
  const assets: RevolutXAsset[] = [];

  for (const rawSymbol of REVOLUT_X_UNIVERSE_USD.symbols) {
    const symbol = rawSymbol.trim().toUpperCase();
    if (!symbol) continue;
    if (seen.has(symbol)) {
      duplicateSymbolsRemoved.push(symbol);
      continue;
    }
    seen.add(symbol);
    assets.push(REVOLUT_X_PROVIDER_IDS[symbol] ?? { symbol });
  }

  return {
    quoteCurrency: REVOLUT_X_UNIVERSE_USD.quoteCurrency,
    source: REVOLUT_X_UNIVERSE_USD.source,
    updatedAt: REVOLUT_X_UNIVERSE_USD.updatedAt,
    rawSymbolCount: REVOLUT_X_UNIVERSE_USD.symbols.length,
    duplicateSymbolsRemoved,
    assets,
    unresolvedSymbols: assets.filter((asset) => !asset.cgId).map((asset) => asset.symbol),
    assumptions: assets.filter((asset) => asset.assumption),
  };
}
